// A chapter to a page that stands on its own (869ermwfv).
//
// The output is a plain static directory: open it, host it, zip it and send it.
// Nothing here is a bundler — the runtime is already plain ES modules with
// relative imports, so the "build" is a prerender plus a copy.
//
// WHAT THE PAGE DOES NOT CONTAIN is the interesting half. No markdown library:
// the prose is HTML by the time this writes it, which is exactly why page.js and
// notebook.js were split — a prerendered chapter needs the wiring, not the
// parser. And no engine on the critical path: 6.2 MB of WebAssembly sits in the
// directory and is fetched the first time somebody presses Run, so the chapter is
// readable with none of it, which is the property this whole project exists for.
//
// NOTHING IS WRITTEN HERE. This returns a MAP of what the directory should
// contain — generated text, or a path to copy — so that `build` can write it,
// `view` can serve it, and a test can read it, without any of the three
// disagreeing about what a page is.
import { renderNotebook } from './render.js';

/** The runtime a page needs. Copied side by side, so their relative imports hold. */
export const RUNTIME = [
  'notebook.js', 'browser.js', 'session.js', 'engine.js', 'worker.js',
  'clauses.js', 'export.js', 'format.js', 'version.js',
];

/** The one engine file: the bundle carries its own data. */
export const ENGINE = 'swipl-bundle.js';

/**
 * The page, as a map of file name to what belongs there.
 *
 * @param {{frontMatter: Map<string,string>, cells: object[]}} notebook parsed
 * @param {string} source the notebook's own bytes, for the download
 * @param {{filename?: string, src?: URL, engine?: URL}} [options]
 *   `src` is the directory holding the runtime modules and `engine` the
 *   directory holding swipl-wasm's bundle — arguments rather than constants so a
 *   test can point them anywhere and an installed package can find its own.
 * @returns {Map<string, {text: string}|{copy: URL}>}
 */
export function buildFiles(notebook, source, options = {}) {
  const {
    filename = 'notebook.prolog.md',
    src = new URL('./', import.meta.url),
    engine = new URL('../node_modules/swipl-wasm/dist/swipl/', import.meta.url),
  } = options;

  const files = new Map();
  files.set('index.html', { text: page(notebook) });
  files.set('app.js', { text: app(source, filename) });
  files.set('notebook.css', { copy: new URL('notebook.css', src) });
  for (const module of RUNTIME) files.set(`lib/${module}`, { copy: new URL(module, src) });
  files.set(`swipl/${ENGINE}`, { copy: new URL(ENGINE, engine) });
  return files;
}

/**
 * The chapter's own title, from its first H1 (format §2).
 *
 * Written into the HTML at build time rather than set by script on load: it is
 * the browser tab, the bookmark and the thing a link preview shows, and none of
 * those wait for JavaScript.
 */
function titleOf(notebook) {
  for (const cell of notebook.cells) {
    if (cell.kind !== 'markdown') continue;
    const heading = /^#\s+(.+)$/m.exec(cell.source);
    if (heading) return heading[1].trim();
  }
  return 'A Prolog notebook';
}

function escapeHtml(text) {
  return String(text).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
}

function page(notebook) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(titleOf(notebook))}</title>
<link rel="stylesheet" href="notebook.css">
</head>
<body>
<main>
${renderNotebook(notebook)}
<!--
  THE CHAPTER ABOVE IS ALREADY READABLE. Everything below is the runtime that
  makes it runnable, and none of it is needed to read a word.
-->
<div id="boot-warning">
  <strong>This notebook is not running.</strong>
  The page loaded but its JavaScript did not. The usual cause is opening
  <code>index.html</code> straight from disk — browsers block ES modules over
  <code>file://</code>. Serve it over HTTP instead, or run
  <code>prolog-notebook view</code> on the notebook itself.
  The chapter is readable either way; only the buttons need this.
</div>
</main>
<script type="module" src="app.js"></script>
</body>
</html>
`;
}

/**
 * The wiring, and the source it hands back when a reader asks for a copy.
 *
 * The notebook's own bytes are embedded because "the chapter as published" has to
 * mean the bytes the author wrote, not a re-serialisation of the model — a
 * hand-written chapter would otherwise come back reformatted.
 */
function app(source, filename) {
  return `// Generated by prolog-notebook build. The chapter is already in index.html;
// this only wires it up.
import { editsOf, mount, offerDownload } from './lib/notebook.js';
import { parse } from './lib/format.js';
import { exportSource } from './lib/export.js';

const SOURCE = ${JSON.stringify(source)};
const FILENAME = ${JSON.stringify(filename)};

const root = document.querySelector('main');
// The engine lives beside this file rather than in a node_modules the browser
// cannot see, so its location is passed rather than guessed.
const cells = mount(root, {
  swiplUrl: new URL('./swipl/${ENGINE}', import.meta.url).href,
});

const notebook = parse(SOURCE);
offerDownload(root, {
  produce: () => ({ filename: FILENAME, text: exportSource(notebook, editsOf(cells)) }),
  published: () => ({ filename: FILENAME, text: SOURCE }),
  isEdited: () => cells.programs.some((p) => p.isEdited())
    || cells.queries.some((q) => q.isEdited()),
  on: cells.on,
});
`;
}
